language: rust
matrix:
  include:
    # linux
    - rust: stable
      os: linux
    - rust: beta
      os: linux
    - rust: nightly
      os: linux
      env: STRICT=true RUSTFMT=true SCRIPTS=true
      if: branch != baked
    - rust: nightly
      os: linux
      env: STRICT=true
      if: branch = baked
    # osx
    - rust: stable
      os: osx
    - rust: beta
      os: osx
    - rust: nightly
      os: osx

# Request the "secret" GCE VM environment (faster + more memory)
sudo: 9000

script:
  - if [ "$STRICT" = true ]; then
      travis_wait cargo build --verbose --all-features;
    else
      travis_wait cargo build --verbose;
    fi
  - if [ "$STRICT" = true ]; then
      travis_wait cargo test --verbose --all-features;
    else
      travis_wait cargo test --verbose;
    fi
  - travis_wait cargo doc --verbose --no-deps
  - if [ "$RUSTFMT" = true ]; then
      travis_wait cargo install --git 'https://github.com/rust-lang-nursery/rustfmt' --verbose;
    fi
  - if [ "$RUSTFMT" = true ]; then pushd cdp; fi
  - if [ "$RUSTFMT" = true ]; then cargo fmt -- --write-mode diff; fi
  - if [ "$RUSTFMT" = true ]; then popd; fi
  - if [ "$RUSTFMT" = true ]; then pushd cdp-definition; fi
  - if [ "$RUSTFMT" = true ]; then cargo fmt -- --write-mode diff; fi
  - if [ "$RUSTFMT" = true ]; then popd; fi
  - if [ "$RUSTFMT" = true ]; then pushd cdp-derive; fi
  - if [ "$RUSTFMT" = true ]; then cargo fmt -- --write-mode diff; fi
  - if [ "$RUSTFMT" = true ]; then popd; fi
  - if [ "$RUSTFMT" = true ]; then pushd tokio-cdp; fi
  - if [ "$RUSTFMT" = true ]; then cargo fmt -- --write-mode diff; fi
  - if [ "$RUSTFMT" = true ]; then popd; fi
  - if [ "$RUSTFMT" = true ]; then
      grep -rL 'This Source Code Form is subject to the terms of the Mozilla Public License' **/src &&
      grep -rL 'This Source Code Form is subject to the terms of the Mozilla Public License' **/tests &&
      grep -rL 'This Source Code Form is subject to the terms of the Mozilla Public License' **.sh;
    fi
  - if [ "$SCRIPTS" = true ]; then ./update-json.sh; fi
  - if [ "$SCRIPTS" = true ]; then ./bake.sh; fi
