language: rust
os:
  - linux
  - osx
rust:
  - stable
  - beta
  - nightly

# Request the "secret" GCE VM environment (faster + more memory)
sudo: 9000

script:
  - travis_wait cargo build --verbose
  - travis_wait cargo test --verbose
  - travis_wait cargo doc --verbose --no-deps

notifications:
  email:
    on_success: never
